name: facebook-connector
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: generate swagger
      run: |
       # Dowloading the swagger client
       wget https://github.com/swaggo/swag/releases/download/v1.7.0/swag_1.7.0_Linux_x86_64.tar.gz
       tar -xvf swag_1.7.0_Linux_x86_64.tar.gz
       ./swag init
       rm swag
       rm swag_1.7.0_Linux_x86_64.tar.gz

    - name: build and deploy
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: ${{ secrets.DOCKER_USERNAME }}/com.fb.srv_facebook-connector
          tags: vCgJQXmQcivBi7GL9YSdtci
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: helm update
      run: |
          # update the helm file
          sed -i 's/:v.*/:vCgJQXmQcivBi7GL9YSdtci/g' helm/templates/service-gen-deployment.yaml

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
           github_token: ${{ secrets.VGITHUB_TOKEN }}
           author_name: Virtuan
           directory: helm
           message: Updating docker tag
           branch: main

